package com.wxx.pswnote.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.wxx.pswnote.bean.Spend;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SPEND".
*/
public class SpendDao extends AbstractDao<Spend, Long> {

    public static final String TABLENAME = "SPEND";

    /**
     * Properties of entity Spend.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Icon = new Property(1, int.class, "icon", false, "ICON");
        public final static Property Spendmoney = new Property(2, String.class, "spendmoney", false, "SPENDMONEY");
        public final static Property Incomemoney = new Property(3, String.class, "incomemoney", false, "INCOMEMONEY");
        public final static Property Type = new Property(4, String.class, "type", false, "TYPE");
        public final static Property Time = new Property(5, String.class, "time", false, "TIME");
        public final static Property Date = new Property(6, String.class, "date", false, "DATE");
    }


    public SpendDao(DaoConfig config) {
        super(config);
    }
    
    public SpendDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SPEND\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ICON\" INTEGER NOT NULL ," + // 1: icon
                "\"SPENDMONEY\" TEXT," + // 2: spendmoney
                "\"INCOMEMONEY\" TEXT," + // 3: incomemoney
                "\"TYPE\" TEXT," + // 4: type
                "\"TIME\" TEXT," + // 5: time
                "\"DATE\" TEXT);"); // 6: date
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SPEND\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Spend entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getIcon());
 
        String spendmoney = entity.getSpendmoney();
        if (spendmoney != null) {
            stmt.bindString(3, spendmoney);
        }
 
        String incomemoney = entity.getIncomemoney();
        if (incomemoney != null) {
            stmt.bindString(4, incomemoney);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(5, type);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(6, time);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(7, date);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Spend entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getIcon());
 
        String spendmoney = entity.getSpendmoney();
        if (spendmoney != null) {
            stmt.bindString(3, spendmoney);
        }
 
        String incomemoney = entity.getIncomemoney();
        if (incomemoney != null) {
            stmt.bindString(4, incomemoney);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(5, type);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(6, time);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(7, date);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Spend readEntity(Cursor cursor, int offset) {
        Spend entity = new Spend( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // icon
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // spendmoney
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // incomemoney
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // type
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // time
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // date
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Spend entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIcon(cursor.getInt(offset + 1));
        entity.setSpendmoney(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIncomemoney(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setType(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDate(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Spend entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Spend entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Spend entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
